### ISSUE TITLE
1.1 releases seem to have broken regex splitting

### ISSUE THREAD

**Issue by mcraig-ibme** [effigies/looseversion#13]
Minimal example:

```
from looseversion import LooseVersion

v = LooseVersion()
v.parse('23.0.04')
print(v.version)
```

Result in 1.0.3:
`[23, 0, 4]`

Result in 1.1.x:
`['', 23, '', '', 0, '', '', 4, '']`

Seems to be related to multiple matches in the regex which causes multiple string splits.

**Comment by effigies** [comment]
Thanks. A dumb mistake on my part. Will fix momentarily.
