### ISSUE TITLE
Question on python permitted suffixes support

### ISSUE THREAD

**Issue by tzing** [effigies/looseversion#25]
Hi,

Although the readme already states that this library is not intended to fully comply with PEP-440, I would like to ask if there is any intention for this library to be compatible with PEP-440 in its design?

PEP-440 suggests some "permitted suffixes" and defines the relationships between these suffixes:

> Within a numeric release (1.0, 2.7.3), the following suffixes are permitted and MUST be ordered as shown:
>
> ```
> .devN, aN, bN, rcN, <no suffix>, .postN
> ```
>
> -- Section "[Summary of permitted suffixes and relative ordering](https://packaging.python.org/en/latest/specifications/version-specifiers/#summary-of-permitted-suffixes-and-relative-ordering)"

However, in this library, all suffixes are treated as additive and considered to be later than numeric version numbers:

```py
In [1]: from looseversion import LooseVersion

In [2]: LooseVersion('1.0.0.a0') < LooseVersion('1.0.0')
Out[2]: False

In [4]: LooseVersion('1.0.0rc1') < LooseVersion('1.0.0')
Out[4]: False

In [5]: LooseVersion('1.0.0') < LooseVersion('1.0.0.dev0')
Out[5]: True

In [6]: LooseVersion('1.0.0') < LooseVersion('1.0.0.post0')
Out[6]: True
```

I feel that in most systems, alpha, beta, and rc versions would typically precede standard numeric version numbers. However, this behavior in the library is somewhat confusing to me.

I would like to ask for your clarification on whether this behavior is expected.

**Comment by effigies** [comment]
> I would like to ask if there is any intention for this library to be compatible with PEP-440 in its design?

No. The entire point is to behave in precisely the way it does, to avoid forcing a change in semantics for libraries that were using it when it existed in the stdlib.

> I feel that in most systems, alpha, beta, and rc versions would typically precede standard numeric version numbers. However, this behavior in the library is somewhat confusing to me.

The behavior is well-defined, but it's not semver or PEP440. If it doesn't match your use case, that's okay. There are other libraries that handle other kinds of version schemes.

**Comment by tzing** [comment]
Got it! Thanks for clarification 😄
