### ISSUE TITLE
installing looseversion v1.0.1 from PyPI source tarball doesn't work as expected

### ISSUE THREAD

**Issue by boegel** [effigies/looseversion#7]
I'm seeing a weird problem when I'm installing from the source tarball obtained from PyPI: it's not actually being installed?

The output below is from macOS 12.6, but I'm also seeing this on a Red Hat Enterprise Linux 8 system using Python 3.9.5 + pip 21.1.1.

```
$  python -V
Python 3.9.6

$ pip --version
pip 21.2.4 from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)

$ curl -OL https://files.pythonhosted.org/packages/5e/f3/17b292003f739362d025cc4b659a604464920cf94714d28c22aa481f5f0c/looseversion-1.0.1.tar.gz
$ tar xfvz looseversion-1.0.1.tar.gz
$ cd looseversion-1.0.1

$ pip install --prefix /tmp/$USER/looseversion .
...
Successfully built looseversion
Installing collected packages: looseversion
Successfully installed looseversion-1.0.1

$ ls /tmp/$USER/looseversion/lib/python3.9/site-packages
looseversion-1.0.1.dist-info

$ cd $HOME
$ PYTHONPATH=/tmp/$USER/looseversion/lib/python3.9/site-packages python -c 'from looseversion import LooseVersion'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'looseversion'
```

Any idea why only a `looseversion-1.0.1.dist-info` directory is being installed (which only contains metadata), and why `looseversion.py` is not being actually installed?

**Comment by effigies** [comment]
I don't know. Does upgrading pip make any difference?

**Comment by boegel** [comment]
No, same problem with pip 22.2.2 . Full output produced by `pip install`:

```
$ pip install --prefix /tmp/$USER/looseversion .
Processing /private/tmp/kehoste/looseversion-1.0.1
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: looseversion
  Building wheel for looseversion (pyproject.toml) ... done
  Created wheel for looseversion: filename=looseversion-1.0.1-py3-none-any.whl size=3235 sha256=e2085c38dc77bd07db12a54e3b70920f7bdf808b8f91cf4147e6142dc6e7a410
  Stored in directory: /Users/kehoste/Library/Caches/pip/wheels/53/3e/db/5a114fc81b49312ae9c4fc653e3e53350a2fa74f9fb111a4ff
Successfully built looseversion
Installing collected packages: looseversion
Successfully installed looseversion-1.0.1
```

Maybe something is missing in `pyproject.toml` to indicate that `looseversion.py` should be installed (since `looseversion` is a single-module package, with no proper Python packages)?

**Comment by merwok** [comment]
Nothing improper about modules that are not packages!

In `setup.py`, the parameter name is `py_modules`, and it’s probably spelled the same way for `setup.cfg`.
Current file is missing the `_`.

**Comment by effigies** [comment]
So `pymodules = looseversion.py` works for building a wheel but seems to be undocumented. It might be an ancient distutils practice...

I think if you change it to `py_modules = looseversion`, that might work. If you figure it out, could you submit a PR?

**Comment by effigies** [comment]
Another option could be to update the build configuration to be entirely in `pyproject.toml`. Since that's a bit more strongly-typed than `setup.cfg`, it might be easier to debug.

**Comment by merwok** [comment]
No, you need `py_modules = looseversion`.

**Comment by effigies** [comment]
@boegel 1.0.2 has been uploaded to PyPI.

**Comment by boegel** [comment]
Thanks a lot, I can confirm that `looseversion` 1.0.2 is working as expected :+1:
